runtime: nodejs14

instance_class: B2

basic_scaling:
  max_instances: 1
  idle_timeout: 10m

env_variables:
  PORT: 8080



handlers:
  - url: /.*
    script: auto

#handlers:
#  - url: /.*
#    static_files: dist/index.html
#    upload: dist/index.html
#  - url: /(.*\.(css|js|map|json|svg|png|jpg|jpeg|gif|ico|woff|woff2|ttf|eot|otf))$
#    static_files: dist/\1
#    upload: dist/.*\.(css|js|map|json|svg|png|jpg|jpeg|gif|ico|woff|woff2|ttf|eot|otf)$
#  - url: /(.+\..+)
#    static_files: dist/\1
#    upload: dist/.+\..+
